### ISSUE TITLE
detect unicode

### ISSUE THREAD

**Issue by stevenvachon** [sindresorhus/is-interactive#1]
[has-unicode](https://npmjs.com/has-unicode)

**Comment by sindresorhus** [comment]
I don't see what that has to do with the terminal being interactive?

The checks in `has-unicode` are also not very good and will mostly be moot in the future as the main reason it exists is the crappy Windows terminal, and it's being replaced by a newer one with full Unicode support.

**Comment by stevenvachon** [comment]
I honestly don't remember why I included it in [supports-semigraphics](https://npmjs.com/supports-semigraphics), but I thought it'd prompt some thinking here. I'll likely deprecate that lib in favour of this.
