### ISSUE TITLE
Why 0.x?

### ISSUE THREAD

**Issue by stevenvachon** [sindresorhus/is-interactive#3]
Are there necessary future plans?

Perhaps `backColorErase`, `canChange`, `clearAllTabs`, `clearScreen`, `clrBol`, `clrEol`, `clrEos`, `deleteChar`, `deleteLine`, `eraseChars` from [terminfo](https://npmjs.com/terminfo)? More info: https://github.com/chalk/supports-color/issues/55#issuecomment-309739964

**Comment by sindresorhus** [comment]
No reason. It's v1.0.0 now. And no, I don't want all those checks.
